// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ4Qz1JWG41lyAWNChaluQm-K7Q_gbHZc',
    appId: '1:349431654241:web:59dcff6494bcd4f92d0720',
    messagingSenderId: '349431654241',
    projectId: 'dairy-distribution-db',
    authDomain: 'dairy-distribution-db.firebaseapp.com',
    storageBucket: 'dairy-distribution-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj_sl_RH2iDb8YNDDWPCyqu-BwgNEMHVw',
    appId: '1:349431654241:android:178eb20ca1cdcc852d0720',
    messagingSenderId: '349431654241',
    projectId: 'dairy-distribution-db',
    storageBucket: 'dairy-distribution-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJo5UYSq3dWf_Q3z2PwPiwJ7kqhsUWr8Q',
    appId: '1:349431654241:ios:7c449dae460ebd3e2d0720',
    messagingSenderId: '349431654241',
    projectId: 'dairy-distribution-db',
    storageBucket: 'dairy-distribution-db.firebasestorage.app',
    iosBundleId: 'com.example.dairyDistributionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJo5UYSq3dWf_Q3z2PwPiwJ7kqhsUWr8Q',
    appId: '1:349431654241:ios:7c449dae460ebd3e2d0720',
    messagingSenderId: '349431654241',
    projectId: 'dairy-distribution-db',
    storageBucket: 'dairy-distribution-db.firebasestorage.app',
    iosBundleId: 'com.example.dairyDistributionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ4Qz1JWG41lyAWNChaluQm-K7Q_gbHZc',
    appId: '1:349431654241:web:6096e39389da73c02d0720',
    messagingSenderId: '349431654241',
    projectId: 'dairy-distribution-db',
    authDomain: 'dairy-distribution-db.firebaseapp.com',
    storageBucket: 'dairy-distribution-db.firebasestorage.app',
  );
}
